---
title: "Playoff Basketball"
author: "Marhawe Asmerom"
date: "5/3/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r Data}

setwd("~/Desktop/Spring2021/Regressions4214/Project") 
NBA <- read.csv("NBAStats2020Regressions.csv", header=TRUE) # imported data from this Regular Season that gives stats per game
summary(NBA)
```







```{r visualization}

NBA$AST_TOV_RATIO = NBA$AST / NBA$TOV
plot(NBA$AST_TOV_RATIO, NBA$Wins, xlab="Assist to Turnover Ratio", ylab= "Wins", pch=19, col="red", main = "Assist / Turnover Ratio Vs Wins") #assist to turnover margin effect winning 


```






```{r}
pairs(Wins ~ FG + ThreePA + ThreePt + TwoPt + OppThreePt + OppTwoPt + AST_TOV_RATIO,data=NBA,gap=0.4,
cex.labels=1.5) # how strong the  correlation between winning and the predictors are , and correlation with predictors 
```


```{r}
Wins2 = lm (Wins ~ FG + ThreePt + ThreePA + TwoPt + OppThreePt + OppTwoPt + AST_TOV_RATIO, data = NBA)
Wins3 = lm (Wins ~ FG + ThreePt + OppThreePt + OppTwoPt + AST_TOV_RATIO, data = NBA) #updating the data to not include 3 point attempts because it was too high 
summary(Wins2)
```


```{r}
summary(Wins3)
```

```{r}
Wins4 = lm (Wins ~ FG + ThreePt + OppThreePt + OppTwoPt + AST_TOV_RATIO , data = NBA) #updating the data to not include 2 point percentage because it was too high

summary(Wins4)
plot(Wins4)

```




```{r}

Wins5 = lm (Wins ~ FG + ThreePt + OppThreePt + OppTwoPt , data = NBA)
plot(predict(Wins5), NBA$Wins,
      xlab="Predicted Wins",ylab="Actual Wins") #projected wins vs wins they actual have this season 
 abline(a=0,b=1)
summary(Wins5)
pairs(Wins ~ FG +  ThreePt +  OppThreePt + OppTwoPt ,data=NBA,gap=0.4,
cex.labels=1.5) 
plot(Wins5)
anova(Wins5,Wins4)
```

```{r}
PlayoffsBound = glm(Playoffs ~ ThreePt + FG + OppThreePt + OppTwoPt
                          , family = binomial, data = NBA)
summary(PlayoffsBound)
```
```{r}
probabilities = predict(PlayoffsBound, type = "response")
PlayoffsEstimates = ifelse(probabilities > 0.5, "Yes", "No")
PlayoffsReal = ifelse(NBA$Playoffs == 1, "Yes", "No")
table(PlayoffsReal, PlayoffsEstimates)
cbind(NBA$Teams, PlayoffsReal, PlayoffsEstimates)
```

